# Experiment parameters
#use_wandb: false

# Data parameters
generate_ngc_data: true
sparsity: 0.9
trainset_size: 1000
tvt_split: 0.5
n_data: &n_data 2
svm: false
sigma_eta_diag: 0.01
sigma_eta_off_diag: 0.
sigma_eps_diag: 1
sigma_eps_off_diag: 0.6
beta_value: 0.9
lags: 1
timesteps: &timesteps 20
normalize_data: false
norm_range_min: -1
norm_range_max: 1
burn_in: 100
stationarity_radius: 0.97
mu_value: 0.025

# Stock data parameters
stock_start: "2000-01-01" # 2008-03-01
stock_end: "2020-01-01" # 2017-02-01
stock_freq: 1d # 10m (5m only possible)
stock_n_obs: 1m # 1d (calculates the RV of the day from 10m data)

# Model parameters
# NGC
ngc:
  max_iter: 1000 # 50000
  layers_size: 100
  num_layers: 1
  lr: 0.05
  lam: 0.002
  lam_ridge: 0.01
  verbose: True

# NRI
nri:
  epochs: 2 # 200
  prediction_steps: 4
  decoder_hidden: 256
  encoder_hidden: 256
  no_cuda: false
  batch_size: 128
  lr: 0.0005
  temp: 0.5
  num_atoms: *n_data
  encoder: mlp
  decoder: mlp
  no_factor: true
  suffix: _springs5
  encoder_dropout: 0
  decoder_dropout: 0
  save_folder: logs
  load_folder: saved_models
  edge_types: 2
  dims: 1
  lr_decay: 200
  gamma: 0.5
  skip_first: true
  var: 0.00005
  hard: false
  prior: false
  dynamic_graph: false
  verbose: True

# tVAR
tvar:
  r_bin_path: C:\Program Files\R\R-4.2.2
  P: 1
  lambda1_opt: 5
  gamma1_opt: 0.2
  verbose: True