# Experiment parameters
experiment: 1a

# Data parameters
c11: &c11 [0.4]
c12: [0.4]
c21: [0.]
c22: *c11
seed: [1, 101, 33, 12, 0]
loader: var # var=1, svm=2, ngc_var=3,stocks=4

# Model parameters
model: [nri, ngc, ngc0, tvar] # nri=1, ngc=2, ngc0=3, tvar=4

# Saving parameters
#use_wandb: False
save_in_dir: True
