stocks:
  - [AAPL, APPLE INC]
  - [KO, COCA-COLA CO]
  - [AXP, AMERICAN EXPRESS CO]
  - [MCD, MCDONALD’S CORP]
  - [BA, BOEING CO]
  - [MMM, 3M]
  - [CAT, CATERPILLAR]
  - [MRK, MERCK & CO]
  - [CSCO, CISCO SYSTEMS]
  - [MSFT, MICROSOFT CORPORATION]
  - [CVX, CHEVRON CORP]
  - [NKE, NIKE INC]
  - [DD, DOW CHEMICAL COMPANY]
  - [PFE, PFIZER INC]
  - [DIS, WALT DISNEY CO]
  - [PG, PROCTER & GAMBLE CO]
  - [GE, GENERAL ELEC]
  - [TRV, TRAVELERS COMPANIES INC]
  - [GS, GOLDMAN SACHS GROUP INC]
  - [UNH, UNITEDHEALTH GROUP INC]
  - [HD, HOME DEPOT INC]
  - [UTX, UNITED TECHNOLOGIES CORPORATION]
  - [IBM, INTL BUS MACHINE]
  - [V, VISA INC]
  - [INTC, INTEL CORP]
  - [VZ, VERIZON COMMUNICATIONS INC]
  - [JNJ, JOHNSON & JOHNSON]
  - [WMT, WALMART INC]
  - [JPM, JPMORGAN CHASE & CO]
  - [XOM, EXXON MOBIL CORPORA]
